### ISSUE TITLE
大佬，能直接跑吗？需要注释掉测试用不到的代码吗

### ISSUE THREAD

**Issue by Big-Smart-h** [cofly2014/CPM-MC#1]
大佬，是不是要注释一部分测试不用的代码，我直接跑ucf 1shot经过2000个iter后验证直接100了。有点怀疑数据泄露了

**Comment by cofly2014** [comment]
您好，感谢关注。
（1）代码应该可以直接跑的，刚才我简单在本地run了一下

（2）ucf数据集本来就很简单，clip预训练模型特征提取能力又很强大，所以在元训练的时候点高其实是正常的，一般这个数据集我记得训练5000到6000次就够了，ssv2稍微长一点时间。在元测试的时候也很高了1-shot大概也快92了（我的1-shot结果不是很好应该没有CLIP-FSAR高）。

（3）最近我在revise一个稿子。等我忙完，我会把github上的代码再整理一下的。另外你说的问题，后续我会跟进一下。​

**Comment by Big-Smart-h** [comment]
我仔细看了一下好像是在`text_eh_temporal_transformer`这个方法中出现的问题，支持集和查询集的特征把真假文本信息都加上了。改了之后ucf最后测试精度有91.9。
![image](https://github.com/user-attachments/assets/3c6cc4c6-cf5d-4293-8bfb-44e7a756d7ef)

**Comment by aasasasaa** [comment]
@D-XH  大佬打扰您一下，请问您是怎么跑这个项目的呢，一直运行那个run_clip_cpmmc文件吗？还是您修改了哪里？非常感谢您的回复

**Comment by cofly2014** [comment]
最近有点忙，稍等我几天，我给你回复。

-----原始邮件-----
发件人:aasasasaa ***@***.***>
发送时间:2025-07-25 10:48:04 (星期五)
收件人: cofly2014/CPM-MC ***@***.***>
抄送: cofly ***@***.***>, Comment ***@***.***>
主题: Re: [cofly2014/CPM-MC] 大佬，能直接跑吗？需要注释掉测试用不到的代码吗 (Issue #1)


aasasasaa left a comment (cofly2014/CPM-MC#1)

@D-XH 大佬打扰您一下，请问您是怎么跑这个项目的呢，一直运行那个run_clip_cpmmc文件吗？还是您修改了哪里？非常感谢您的回复
